services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0 -p 3000"
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
    environment:
      - GOOGLE_CLIENT_ID=1012296461031-0055gggn7tn2qee6oicg2korn1lmhrro.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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